#!/bin/bash

export WHITE="\e[0m";
export RED="\e[0;31m";
export ORANGE="\e[1;31m";
export GREEN="\e[0;32m";
export LIME="\e[1;32m";
export GOLD="\e[0;33m";
export YELLOW="\e[1;33m";
export INDIGO="\e[0;34m";
export BLUE="\e[1;34m";
export VIOLET="\e[0;35m";
export PINK="\e[1;35m";
export DARK_CYAN="\e[0;36m";
export CYAN="\e[1;36m";export RED='\e[0;31m';
export GRAY="\e[0;37m";
export GREY=$GRAY #because reasons...

export RED_HIGHLIGHTED="\e[0;41m";
export GREEN_HIGHLIGHTED="\e[0;42m";
export YELLOW_HIGHLIGHTED="\e[0;43m";
export BLUE_HIGHLIGHTED="\e[0;44m";
export PURPLE_HIGHLIGHTED="\e[0;45m";
export CYAN_HIGHLIGHTED="\e[0;46m";
export GRAY_HIGHLIGHTED="\e[0;47m";
