#!/bin/bash

function state_home(){
    header "Welcome to Agnokar's fueling station"
    header "Please choose what to do"
    option 1 "Select fuel type"
    option 2 "Select payment method"
    local message=""
    if [[ $FUEL_TO_BUY -eq 0 ]]; then
	message="Exit"
    else
	message="Pay and exit"
    fi
    option 3 $message
    getRangeNumberInput 1 3
    case $INPUT in
	1)
	    CURRENT_STATE=$STATE_SELECT_FUEL
	    ;;
	2)
	    CURRENT_STATE=$STATE_SELECT_PAYMENT
	    ;;
	3)
	    if [[ $FUEL_TO_BUY -eq 0 ]]; then
		CURRENT_STATE=$STATE_EXIT
	    else
		CURRENT_STATE=$STATE_PAY
	    fi
	    ;;
    esac
    unset INPUT
}

